-- MySQL Script generated by MySQL Workbench
-- Sat Dec 15 09:14:48 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema exame
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema exame
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `exame` DEFAULT CHARACTER SET utf8 ;
USE `exame` ;

-- -----------------------------------------------------
-- Table `exame`.`Aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exame`.`Aluno` (
  `alu_matricula` INT(12) NOT NULL COMMENT 'Matrícula do Aluno',
  `alu_nome` VARCHAR(45) NOT NULL COMMENT 'Nome completo do aluno',
  PRIMARY KEY (`alu_matricula`),
  UNIQUE INDEX `matricula_UNIQUE` (`alu_matricula` ASC) VISIBLE,
  UNIQUE INDEX `nome_UNIQUE` (`alu_nome` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exame`.`AlunoGrad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exame`.`AlunoGrad` (
  `alg_alu_matricula` INT(12) NOT NULL COMMENT 'Chave extrangeira matricula do aluno',
  INDEX `alg_alu_matricula_idx` (`alg_alu_matricula` ASC) VISIBLE,
  CONSTRAINT `alg_alu_matricula`
    FOREIGN KEY (`alg_alu_matricula`)
    REFERENCES `exame`.`Aluno` (`alu_matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exame`.`AlunoPos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exame`.`AlunoPos` (
  `alp_alu_matricula` INT(12) NOT NULL COMMENT 'Chave extrangeira da matrícula do Aluno',
  `alp_agenciaBolsa` VARCHAR(45) NULL COMMENT 'Núcleo que gerencia a bolsa de estudos do aluno',
  INDEX `alp_alu_matricula_idx` (`alp_alu_matricula` ASC) VISIBLE,
  CONSTRAINT `alp_alu_matricula`
    FOREIGN KEY (`alp_alu_matricula`)
    REFERENCES `exame`.`Aluno` (`alu_matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exame`.`Professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exame`.`Professor` (
  `pro_matricula` INT(12) NOT NULL COMMENT 'Matrícula do Professor',
  `pro_nome` VARCHAR(45) NULL COMMENT 'Nome do professor',
  PRIMARY KEY (`pro_matricula`),
  UNIQUE INDEX `matricula_UNIQUE` (`pro_matricula` ASC) VISIBLE,
  UNIQUE INDEX `nome_UNIQUE` (`pro_nome` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exame`.`Dissertacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exame`.`Dissertacao` (
  `id` INT(12) NOT NULL COMMENT 'Identifica��o da dissertação',
  `tipo` VARCHAR(45) NULL COMMENT 'Tipo de dissertação',
  `ano` DATE NULL COMMENT 'Ano da Dissertação',
  `titulo` VARCHAR(45) NULL COMMENT 'Título da Dissertação',
  `dir_alp_alu_matricula` INT(12) NULL COMMENT 'Chave extrangeira da matricula do aluno',
  `dir_pro_matricula` INT(12) NULL COMMENT 'Chave extrangeira da matrícula do professor',
  PRIMARY KEY (`id`),
  INDEX `dir_alp_alu_matricula_idx` (`dir_alp_alu_matricula` ASC) VISIBLE,
  INDEX `dir_pro_matricula_idx` (`dir_pro_matricula` ASC) VISIBLE,
  CONSTRAINT `dir_alp_alu_matricula`
    FOREIGN KEY (`dir_alp_alu_matricula`)
    REFERENCES `exame`.`AlunoPos` (`alp_alu_matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `dir_pro_matricula`
    FOREIGN KEY (`dir_pro_matricula`)
    REFERENCES `exame`.`Professor` (`pro_matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
